services:
  seeder:
    build:
      context: .
      dockerfile: seeder.Dockerfile

      args:
        EXECUTE_ENV_PATH: ${EXECUTE_ENV_PATH}
        SEEDER_EXTERNAL_RPC_URL: ${SEEDER_EXTERNAL_RPC_URL}
        SEEDER_INTERNAL_RPC_URL: ${SEEDER_INTERNAL_RPC_URL}
        RPC_CALL_ENV_PATH: ${RPC_CALL_ENV_PATH}
        LIVENESS_PLATFORM: ${LIVENESS_PLATFORM}
        LIVENESS_SERVICE_PROVIDER: ${LIVENESS_SERVICE_PROVIDER}
        LIVENESS_RPC_URL: ${LIVENESS_RPC_URL}
        LIVENESS_WS_URL: ${LIVENESS_WS_URL}
        LIVENESS_CONTRACT_ADDRESS: ${LIVENESS_CONTRACT_ADDRESS}

    container_name: seeder

    environment:
      MODE: ${MODE}

    ports:
      - "6000:6000"
      - "6001:6001"

    volumes:
      - ../seeder/data:/app/seeder/data

    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        cat ./scripts/execute/env.sh
        cat ./scripts/execute/01_init_seeder.sh

        if [ "$MODE" = "init" ]; then
          echo "🚀 Running Seeder Initialization..."
          ./scripts/execute/01_init_seeder.sh
          # cat ./data/Config.toml
          ./scripts/execute/02_run_seeder.sh &
          sleep 5
          ./scripts/rpc-call/10_initialize.sh
          
          tail -f /dev/null

        elif [ "$MODE" = "run" ]; then
          echo "🚀 Running Seeder..."
          ./scripts/execute/02_run_seeder.sh &

          tail -f /dev/null

        else
          echo "❌ Invalid MODE: ${MODE}"
          exit 1
        fi
