version: "3.8"

services:
  seeder:
    build:
      context: .
      dockerfile: seeder.Dockerfile
    container_name: seeder
    environment:
      # Seeder Execution Environment Variables
      SEEDER_EXTERNAL_RPC_URL: "http://127.0.0.1:6000"
      SEEDER_INTERNAL_RPC_URL: "http://127.0.0.1:6001"

      # Seeder RPC-Call Environment Variables
      LIVENESS_PLATFORM: "ethereum"
      LIVENESS_SERVICE_PROVIDER: "radius"
      LIVENESS_RPC_URL: "http://127.0.0.1:8545"
      LIVENESS_WS_URL: "ws://127.0.0.1:8545"
      LIVENESS_CONTRACT_ADDRESS: "0x0000000000000000000000000000000000000000"
    ports:
      - "6000:6000"
      - "6001:6001"
    volumes:
      - ../seeder/data:/app/seeder/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        cd /app/seeder
        ./scripts/execute/01_init_seeder.sh
        ./scripts/execute/02_run_seeder.sh
        ./scripts/rpc-call/10_initialize.sh

  key_generator:
    build:
      context: .
      dockerfile: key_generator.Dockerfile
    container_name: key_generator
    environment:
      # DKG Execution Environment Variables
      KEY_GENERATOR_INTERNAL_RPC_URL: "http://127.0.0.1:7200"
      KEY_GENERATOR_CLUSTER_RPC_URL: "http://127.0.0.1:7300"
      KEY_GENERATOR_EXTERNAL_RPC_URL: "http://127.0.0.1:7100"
      KEY_GENERATOR_ADDRESS: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    depends_on:
      - seeder
    ports:
      - "7100:7100"
      - "7200:7200"
      - "7300:7300"
    volumes:
      - ../distributed_key_generation/data:/app/distributed_key_generation/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        cd /app/distributed_key_generation
        ./scripts/execute/01_init_key_generator.sh
        ./scripts/execute/02_run_key_generator.sh
        ./scripts/rpc-call/10_initialize.sh
