FROM rust:1.75 as builder

WORKDIR /app

RUN git clone https://github.com/gylman/distributed_key_generation-gylman && mv distributed_key_generation-gylman key_generator

WORKDIR /app/key_generator

RUN apt-get update && apt-get install -y git clang llvm-dev libclang-dev cmake pkg-config build-essential libssl-dev
RUN cargo build --release

FROM ubuntu:22.04

WORKDIR /app/key_generator

RUN apt-get update && apt-get install -y curl

COPY --from=builder /app/key_generator/scripts /app/key_generator/scripts
COPY --from=builder /app/key_generator/target/release/key-generator /app/key_generator/target/release/key-generator

ARG KEY_GENERATOR_EXECUTE_ENV_PATH
ARG KEY_GENERATOR_RPC_CALL_ENV_PATH
ARG KEY_GENERATOR_INTERNAL_RPC_URL
ARG KEY_GENERATOR_CLUSTER_RPC_URL
ARG KEY_GENERATOR_EXTERNAL_RPC_URL
ARG KEY_GENERATOR_ADDRESS
ARG KEY_GENERATOR_PRIVATE_KEY

RUN echo "KEY_GENERATOR_INTERNAL_RPC_URL=${KEY_GENERATOR_INTERNAL_RPC_URL}"
RUN echo "KEY_GENERATOR_CLUSTER_RPC_URL=${KEY_GENERATOR_CLUSTER_RPC_URL}"
RUN echo "KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}"
RUN echo "KEY_GENERATOR_ADDRESS=${KEY_GENERATOR_ADDRESS}"
RUN echo "KEY_GENERATOR_PRIVATE_KEY=${KEY_GENERATOR_PRIVATE_KEY}"

RUN cp /app/key_generator/scripts/execute/env_example.sh ${KEY_GENERATOR_EXECUTE_ENV_PATH}
RUN cp /app/key_generator/scripts/rpc-call/env_example.sh ${KEY_GENERATOR_RPC_CALL_ENV_PATH}

RUN sed -i "s|KEY_GENERATOR_INTERNAL_RPC_URL=.*|KEY_GENERATOR_INTERNAL_RPC_URL=${KEY_GENERATOR_INTERNAL_RPC_URL}|" ${KEY_GENERATOR_EXECUTE_ENV_PATH} 
RUN sed -i "s|KEY_GENERATOR_CLUSTER_RPC_URL=.*|KEY_GENERATOR_CLUSTER_RPC_URL=${KEY_GENERATOR_CLUSTER_RPC_URL}|" ${KEY_GENERATOR_EXECUTE_ENV_PATH} 
RUN sed -i "s|KEY_GENERATOR_EXTERNAL_RPC_URL=.*|KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}|" ${KEY_GENERATOR_EXECUTE_ENV_PATH} 
RUN sed -i "s|KEY_GENERATOR_PRIVATE_KEY=.*|KEY_GENERATOR_PRIVATE_KEY=${KEY_GENERATOR_PRIVATE_KEY}|" ${KEY_GENERATOR_EXECUTE_ENV_PATH} 
RUN sed -i "s|KEY_GENERATOR_INTERNAL_RPC_URL=.*|KEY_GENERATOR_INTERNAL_RPC_URL=${KEY_GENERATOR_INTERNAL_RPC_URL}|" ${KEY_GENERATOR_RPC_CALL_ENV_PATH}
RUN sed -i "s|KEY_GENERATOR_CLUSTER_RPC_URL=.*|KEY_GENERATOR_CLUSTER_RPC_URL=${KEY_GENERATOR_CLUSTER_RPC_URL}|" ${KEY_GENERATOR_RPC_CALL_ENV_PATH}
RUN sed -i "s|KEY_GENERATOR_EXTERNAL_RPC_URL=.*|KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}|" ${KEY_GENERATOR_RPC_CALL_ENV_PATH}
RUN sed -i "s|KEY_GENERATOR_ADDRESS=.*|KEY_GENERATOR_ADDRESS=${KEY_GENERATOR_ADDRESS}|" ${KEY_GENERATOR_RPC_CALL_ENV_PATH}