FROM rust:1.75 as builder

WORKDIR /app

RUN git clone https://github.com/radiusxyz/secure-rpc && mv secure-rpc secure-rpc-provider

WORKDIR /app/secure-rpc-provider

RUN apt-get update && apt-get install -y git clang llvm-dev libclang-dev cmake pkg-config build-essential libssl-dev
RUN cargo build --release

FROM ubuntu:22.04

WORKDIR /app/secure-rpc-provider

RUN apt-get update && apt-get install -y curl

COPY --from=builder /app/secure-rpc-provider/scripts /app/secure-rpc-provider/scripts
COPY --from=builder /app/secure-rpc-provider/target/release/key-generator /app/secure-rpc-provider/target/release/key-generator

ARG SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH
ARG SECURE_RPC_EXTERNAL_RPC_URL
ARG SEQUENCER_RPC_URL
ARG ENCRYPTED_TRANSACTION_TYPE
ARG ROLLUP_ID
ARG ROLLUP_RPC_URL
ARG SECURE_RPC_PROVIDER_PRIVATE_KEY
ARG KEY_GENERATOR_EXTERNAL_RPC_URL

RUN echo "SECURE_RPC_MODE=${SECURE_RPC_MODE}"
RUN echo "SECURE_RPC_EXTERNAL_RPC_URL=${SECURE_RPC_EXTERNAL_RPC_URL}"
RUN echo "SECURE_RPC_PROVIDER_PRIVATE_KEY=${SECURE_RPC_PROVIDER_PRIVATE_KEY}"

RUN echo "SEQUENCER_RPC_URL=${SEQUENCER_RPC_URL}"
RUN echo "ENCRYPTED_TRANSACTION_TYPE=${ENCRYPTED_TRANSACTION_TYPE}"

RUN echo "ROLLUP_ID=${ROLLUP_ID}"
RUN echo "ROLLUP_RPC_URL=${ROLLUP_RPC_URL}"
RUN echo "KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}"

RUN cp /app/secure-rpc-provider/scripts/execute/env_example.sh ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}

RUN sed -i "s|SECURE_RPC_PROVIDER_INTERNAL_RPC_URL=.*|SECURE_RPC_PROVIDER_INTERNAL_RPC_URL=${SECURE_RPC_PROVIDER_INTERNAL_RPC_URL}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
RUN sed -i "s|SECURE_RPC_PROVIDER_CLUSTER_RPC_URL=.*|SECURE_RPC_PROVIDER_CLUSTER_RPC_URL=${SECURE_RPC_PROVIDER_CLUSTER_RPC_URL}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
RUN sed -i "s|SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL=.*|SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL=${SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
RUN sed -i "s|SECURE_RPC_PROVIDER_PRIVATE_KEY=.*|SECURE_RPC_PROVIDER_PRIVATE_KEY=${SECURE_RPC_PROVIDER_PRIVATE_KEY}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}

RUN sed -i "s|ROLLUP_ID=.*|ROLLUP_ID=${ROLLUP_ID}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
RUN sed -i "s|ROLLUP_RPC_URL=.*|ROLLUP_RPC_URL=${ROLLUP_RPC_URL}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}

RUN sed -i "s|KEY_GENERATOR_EXTERNAL_RPC_URL=.*|KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}|" ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}