FROM rust:1.75 as builder

WORKDIR /app

RUN git clone https://github.com/gylman/seeder-gylman && mv seeder-gylman seeder

WORKDIR /app/seeder

RUN apt-get update && apt-get install -y git clang llvm-dev libclang-dev cmake pkg-config build-essential libssl-dev 
RUN cargo build --release

FROM ubuntu:22.04

WORKDIR /app/seeder

RUN apt-get update && apt-get install -y curl

COPY --from=builder /app/seeder/scripts /app/seeder/scripts
COPY --from=builder /app/seeder/target/release/seeder /app/seeder/target/release/seeder

ARG SEEDER_EXECUTE_ENV_PATH
ARG SEEDER_EXTERNAL_RPC_URL
ARG SEEDER_INTERNAL_RPC_URL
ARG SEEDER_RPC_CALL_ENV_PATH

ARG LIVENESS_PLATFORM
ARG LIVENESS_SERVICE_PROVIDER
ARG LIVENESS_RPC_URL
ARG LIVENESS_WS_URL
ARG LIVENESS_CONTRACT_ADDRESS

RUN echo "SEEDER_EXECUTE_ENV_PATH=${SEEDER_EXECUTE_ENV_PATH}"
RUN echo "SEEDER_RPC_CALL_ENV_PATH=${SEEDER_RPC_CALL_ENV_PATH}"
RUN echo "SEEDER_EXTERNAL_RPC_URL=${SEEDER_EXTERNAL_RPC_URL}"
RUN echo "SEEDER_INTERNAL_RPC_URL=${SEEDER_INTERNAL_RPC_URL}"

RUN echo "LIVENESS_PLATFORM=${LIVENESS_PLATFORM}"
RUN echo "LIVENESS_SERVICE_PROVIDER=${LIVENESS_SERVICE_PROVIDER}"
RUN echo "LIVENESS_RPC_URL=${LIVENESS_RPC_URL}"
RUN echo "LIVENESS_WS_URL=${LIVENESS_WS_URL}"
RUN echo "LIVENESS_CONTRACT_ADDRESS=${LIVENESS_CONTRACT_ADDRESS}"

RUN cp /app/seeder/scripts/execute/env_example.sh ${SEEDER_EXECUTE_ENV_PATH}
RUN cp /app/seeder/scripts/rpc-call/env_example.sh ${SEEDER_RPC_CALL_ENV_PATH}
 
RUN sed -i "s|SEEDER_EXTERNAL_RPC_URL=.*|SEEDER_EXTERNAL_RPC_URL=${SEEDER_EXTERNAL_RPC_URL}|" ${SEEDER_EXECUTE_ENV_PATH}
RUN sed -i "s|SEEDER_INTERNAL_RPC_URL=.*|SEEDER_INTERNAL_RPC_URL=${SEEDER_INTERNAL_RPC_URL}|" ${SEEDER_EXECUTE_ENV_PATH}
RUN sed -i "s|SEEDER_INTERNAL_RPC_URL=.*|SEEDER_INTERNAL_RPC_URL=${SEEDER_INTERNAL_RPC_URL}|" ${SEEDER_RPC_CALL_ENV_PATH}

RUN sed -i "s|LIVENESS_PLATFORM=.*|LIVENESS_PLATFORM=${LIVENESS_PLATFORM}|" ${SEEDER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_SERVICE_PROVIDER=.*|LIVENESS_SERVICE_PROVIDER=${LIVENESS_SERVICE_PROVIDER}|" ${SEEDER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_RPC_URL=.*|LIVENESS_RPC_URL=${LIVENESS_RPC_URL}|" ${SEEDER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_WS_URL=.*|LIVENESS_WS_URL=${LIVENESS_WS_URL}|" ${SEEDER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_CONTRACT_ADDRESS=.*|LIVENESS_CONTRACT_ADDRESS=${LIVENESS_CONTRACT_ADDRESS}|" ${SEEDER_RPC_CALL_ENV_PATH}
