FROM rust:1.75 as builder

WORKDIR /app

RUN git clone https://github.com/gylman/tx_orderer

WORKDIR /app/tx_orderer

RUN apt-get update && apt-get install -y git clang llvm-dev libclang-dev cmake pkg-config build-essential libssl-dev
RUN cargo build --release

FROM ubuntu:22.04

WORKDIR /app/tx_orderer

RUN apt-get update && apt-get install -y curl

COPY --from=builder /app/tx_orderer/scripts /app/tx_orderer/scripts
COPY --from=builder /app/tx_orderer/target/release/sequencer /app/tx_orderer/target/release/sequencer

ARG LIVENESS_PLATFORM
ARG LIVENESS_SERVICE_PROVIDER
ARG LIVENESS_RPC_URL
ARG LIVENESS_WS_URL
ARG LIVENESS_CONTRACT_ADDRESS

ARG CLUSTER_ID

ARG VALIDATION_PLATFORM
ARG VALIDATION_SERVICE_PROVIDER
ARG VALIDATION_RPC_URL
ARG VALIDATION_WS_URL
ARG VALIDATION_SERVICE_MANAGER_CONTRACT_ADDRESS

ARG SEQUENCER_EXECUTE_ENV_PATH
ARG SEQUENCER_RPC_CALL_ENV_PATH
ARG SEQUENCER_INTERNAL_RPC_URL
ARG SEQUENCER_EXTERNAL_RPC_URL
ARG SEQUENCER_CLUSTER_RPC_URL
ARG SEQUENCER_PRIVATE_KEY

ARG KEY_GENERATOR_EXTERNAL_RPC_URL
ARG SEEDER_EXTERNAL_RPC_URL

RUN echo "SEQUENCER_INTERNAL_RPC_URL=${SEQUENCER_INTERNAL_RPC_URL}"
RUN echo "SEQUENCER_EXTERNAL_RPC_URL=${SEQUENCER_EXTERNAL_RPC_URL}"
RUN echo "SEQUENCER_CLUSTER_RPC_URL=${SEQUENCER_CLUSTER_RPC_URL}"
RUN echo "SEQUENCER_PRIVATE_KEY=${SEQUENCER_PRIVATE_KEY}"
RUN echo "KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}"
RUN echo "SEEDER_EXTERNAL_RPC_URL=${SEEDER_EXTERNAL_RPC_URL}"

RUN cp /app/tx_orderer/scripts/execute/env_example.sh ${SEQUENCER_EXECUTE_ENV_PATH}
RUN cp /app/tx_orderer/scripts/rpc-call/env_example.sh ${SEQUENCER_RPC_CALL_ENV_PATH}

RUN sed -i "s|LIVENESS_PLATFORM=.*|LIVENESS_PLATFORM=${LIVENESS_PLATFORM}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_SERVICE_PROVIDER=.*|LIVENESS_SERVICE_PROVIDER=${LIVENESS_SERVICE_PROVIDER}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_RPC_URL=.*|LIVENESS_RPC_URL=${LIVENESS_RPC_URL}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_WS_URL=.*|LIVENESS_WS_URL=${LIVENESS_WS_URL}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|LIVENESS_CONTRACT_ADDRESS=.*|LIVENESS_CONTRACT_ADDRESS=${LIVENESS_CONTRACT_ADDRESS}|" ${SEQUENCER_RPC_CALL_ENV_PATH}

RUN sed -i "s|CLUSTER_ID=.*|CLUSTER_ID=${CLUSTER_ID}|" ${SEQUENCER_RPC_CALL_ENV_PATH}

RUN sed -i "s|VALIDATION_PLATFORM=.*|VALIDATION_PLATFORM=${VALIDATION_PLATFORM}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|VALIDATION_SERVICE_PROVIDER=.*|VALIDATION_SERVICE_PROVIDER=${VALIDATION_SERVICE_PROVIDER}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|VALIDATION_RPC_URL=.*|VALIDATION_RPC_URL=${VALIDATION_RPC_URL}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|VALIDATION_WS_URL=.*|VALIDATION_WS_URL=${VALIDATION_WS_URL}|" ${SEQUENCER_RPC_CALL_ENV_PATH}
RUN sed -i "s|VALIDATION_SERVICE_MANAGER_CONTRACT_ADDRESS=.*|VALIDATION_SERVICE_MANAGER_CONTRACT_ADDRESS=${VALIDATION_SERVICE_MANAGER_CONTRACT_ADDRESS}|" ${SEQUENCER_RPC_CALL_ENV_PATH}

RUN sed -i "s|SEQUENCER_INTERNAL_RPC_URL=.*|SEQUENCER_INTERNAL_RPC_URL=${SEQUENCER_INTERNAL_RPC_URL}|" ${SEQUENCER_EXECUTE_ENV_PATH} 
RUN sed -i "s|SEQUENCER_EXTERNAL_RPC_URL=.*|SEQUENCER_EXTERNAL_RPC_URL=${SEQUENCER_EXTERNAL_RPC_URL}|" ${SEQUENCER_EXECUTE_ENV_PATH} 
RUN sed -i "s|SEQUENCER_CLUSTER_RPC_URL=.*|SEQUENCER_CLUSTER_RPC_URL=${SEQUENCER_CLUSTER_RPC_URL}|" ${SEQUENCER_EXECUTE_ENV_PATH} 
RUN sed -i "s|SEQUENCER_PRIVATE_KEY=.*|SEQUENCER_PRIVATE_KEY=${SEQUENCER_PRIVATE_KEY}|" ${SEQUENCER_EXECUTE_ENV_PATH} 
RUN sed -i "s|SEQUENCER_INTERNAL_RPC_URL=.*|SEQUENCER_INTERNAL_RPC_URL=${SEQUENCER_INTERNAL_RPC_URL}|" ${SEQUENCER_EXECUTE_ENV_PATH}
RUN sed -i "s|SEQUENCER_INTERNAL_RPC_URL=.*|SEQUENCER_INTERNAL_RPC_URL=${SEQUENCER_INTERNAL_RPC_URL}|" ${SEQUENCER_RPC_CALL_ENV_PATH}

RUN sed -i "s|KEY_GENERATOR_EXTERNAL_RPC_URL=.*|KEY_GENERATOR_EXTERNAL_RPC_URL=${KEY_GENERATOR_EXTERNAL_RPC_URL}|" ${SEQUENCER_EXECUTE_ENV_PATH} 

RUN sed -i "s|SEEDER_EXTERNAL_RPC_URL=.*|SEEDER_EXTERNAL_RPC_URL=${SEEDER_EXTERNAL_RPC_URL}|" ${SEQUENCER_EXECUTE_ENV_PATH} 